language: objective-c # don't worry - works with swift too!
osx_image: xcode7.2
before_install:
  - npm install -g bower
install:
  - cd www && bower install && cd ..
script:
  #xctool doesn't seem to work with UI tests
  - xcodebuild test -project ios/demo.xcodeproj/ -scheme demo -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=YES
